package org.compiere.model;

import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Generated Interface for M_MovementLineMA
 *
 * @author iDempiere (generated)
 * @version Release 5.1
 */
public interface I_M_MovementLineMA {

    /**
     * TableName=M_MovementLineMA
     */
    String Table_Name = "M_MovementLineMA";

    /**
     * AD_Table_ID=764
     */
    int Table_ID = 764;

    /**
     * AccessLevel = 1 - Org
     */
    BigDecimal accessLevel = BigDecimal.valueOf(1);


    /**
     * Column name DateMaterialPolicy
     */
    String COLUMNNAME_DateMaterialPolicy = "DateMaterialPolicy";
    /**
     * Column name IsAutoGenerated
     */
    String COLUMNNAME_IsAutoGenerated = "IsAutoGenerated";
    /**
     * Column name M_AttributeSetInstance_ID
     */
    String COLUMNNAME_M_AttributeSetInstance_ID = "M_AttributeSetInstance_ID";
    /**
     * Column name M_MovementLine_ID
     */
    String COLUMNNAME_M_MovementLine_ID = "M_MovementLine_ID";
    /**
     * Column name MovementQty
     */
    String COLUMNNAME_MovementQty = "MovementQty";

    /**
     * Get Date Material Policy. Time used for LIFO and FIFO Material Policy
     */
    Timestamp getDateMaterialPolicy();

    /**
     * Set Date Material Policy. Time used for LIFO and FIFO Material Policy
     */
    void setDateMaterialPolicy(Timestamp DateMaterialPolicy);

    /**
     * Set Auto Generated
     */
    void setIsAutoGenerated(boolean IsAutoGenerated);

    /**
     * Get Auto Generated
     */
    boolean isAutoGenerated();

    /**
     * Get Attribute Set Instance. Product Attribute Set Instance
     */
    int getAttributeSetInstanceId();

    /**
     * Set Attribute Set Instance. Product Attribute Set Instance
     */
    void setAttributeSetInstanceId(int M_AttributeSetInstance_ID);

    /**
     * Get Move Line. Inventory Move document Line
     */
    int getMovementLineId();

    /**
     * Set Move Line. Inventory Move document Line
     */
    void setMovementLineId(int M_MovementLine_ID);

    I_M_MovementLine getMovementLine() throws RuntimeException;

    /**
     * Get Movement Quantity. Quantity of a product moved.
     */
    BigDecimal getMovementQty();

    /**
     * Set Movement Quantity. Quantity of a product moved.
     */
    void setMovementQty(BigDecimal MovementQty);

}
