package org.compiere.model;

import java.math.BigDecimal;
import java.sql.Timestamp;
import org.idempiere.common.util.KeyNamePair;

/**
 * Generated Interface for M_MovementLineMA
 *
 * @author iDempiere (generated)
 * @version Release 5.1
 */
public interface I_M_MovementLineMA {

  /** TableName=M_MovementLineMA */
  String Table_Name = "M_MovementLineMA";

  /** AD_Table_ID=764 */
  int Table_ID = 764;

  KeyNamePair Model = new KeyNamePair(Table_ID, Table_Name);

  /** AccessLevel = 1 - Org */
  BigDecimal accessLevel = BigDecimal.valueOf(1);

  /** Load Meta Data */

  /** Column name AD_Org_ID */
  String COLUMNNAME_AD_Org_ID = "AD_Org_ID";
  /** Column name Created */
  String COLUMNNAME_Created = "Created";
  /** Column name CreatedBy */
  String COLUMNNAME_CreatedBy = "CreatedBy";
  /** Column name DateMaterialPolicy */
  String COLUMNNAME_DateMaterialPolicy = "DateMaterialPolicy";
  /** Column name IsActive */
  String COLUMNNAME_IsActive = "IsActive";
  /** Column name IsAutoGenerated */
  String COLUMNNAME_IsAutoGenerated = "IsAutoGenerated";
  /** Column name M_AttributeSetInstance_ID */
  String COLUMNNAME_M_AttributeSetInstance_ID = "M_AttributeSetInstance_ID";
  /** Column name M_MovementLine_ID */
  String COLUMNNAME_M_MovementLine_ID = "M_MovementLine_ID";
  /** Column name M_MovementLineMA_UU */
  String COLUMNNAME_M_MovementLineMA_UU = "M_MovementLineMA_UU";
  /** Column name MovementQty */
  String COLUMNNAME_MovementQty = "MovementQty";
  /** Column name Updated */
  String COLUMNNAME_Updated = "Updated";
  /** Column name UpdatedBy */
  String COLUMNNAME_UpdatedBy = "UpdatedBy";

  /** Set Organization. Organizational entity within client */
  void setAD_Org_ID(int AD_Org_ID);

  /** Get Organization. Organizational entity within client */
  int getOrgId();

  /** Get Created. Date this record was created */
  Timestamp getCreated();

  /** Get Created By. User who created this records */
  int getCreatedBy();

  /** Get Date Material Policy. Time used for LIFO and FIFO Material Policy */
  Timestamp getDateMaterialPolicy();

  /** Set Date Material Policy. Time used for LIFO and FIFO Material Policy */
  void setDateMaterialPolicy(Timestamp DateMaterialPolicy);

  /** Set Active. The record is active in the system */
  void setIsActive(boolean IsActive);

  /** Get Active. The record is active in the system */
  boolean isActive();

  /** Set Auto Generated */
  void setIsAutoGenerated(boolean IsAutoGenerated);

  /** Get Auto Generated */
  boolean isAutoGenerated();

  /** Set Attribute Set Instance. Product Attribute Set Instance */
  void setM_AttributeSetInstance_ID(int M_AttributeSetInstance_ID);

  /** Get Attribute Set Instance. Product Attribute Set Instance */
  int getMAttributeSetInstance_ID();

  I_M_AttributeSetInstance getMAttributeSetInstance() throws RuntimeException;

  /** Get Move Line. Inventory Move document Line */
  int getM_MovementLine_ID();

  /** Set Move Line. Inventory Move document Line */
  void setM_MovementLine_ID(int M_MovementLine_ID);

  I_M_MovementLine getM_MovementLine() throws RuntimeException;

  /** Get M_MovementLineMA_UU */
  String getM_MovementLineMA_UU();

  /** Set M_MovementLineMA_UU */
  void setM_MovementLineMA_UU(String M_MovementLineMA_UU);

  /** Get Movement Quantity. Quantity of a product moved. */
  BigDecimal getMovementQty();

  /** Set Movement Quantity. Quantity of a product moved. */
  void setMovementQty(BigDecimal MovementQty);

  /** Get Updated. Date this record was updated */
  Timestamp getUpdated();

  /** Get Updated By. User who updated this records */
  int getUpdatedBy();
}
