package org.compiere.model;

import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Generated Interface for M_InventoryLineMA
 *
 * @author iDempiere (generated)
 * @version Release 5.1
 */
public interface I_M_InventoryLineMA {

    /**
     * TableName=M_InventoryLineMA
     */
    String Table_Name = "M_InventoryLineMA";

    /**
     * AD_Table_ID=763
     */
    int Table_ID = 763;

    /**
     * AccessLevel = 1 - Org
     */
    BigDecimal accessLevel = BigDecimal.valueOf(1);


    /**
     * Column name DateMaterialPolicy
     */
    String COLUMNNAME_DateMaterialPolicy = "DateMaterialPolicy";
    /**
     * Column name IsAutoGenerated
     */
    String COLUMNNAME_IsAutoGenerated = "IsAutoGenerated";
    /**
     * Column name M_AttributeSetInstance_ID
     */
    String COLUMNNAME_M_AttributeSetInstance_ID = "M_AttributeSetInstance_ID";
    /**
     * Column name M_InventoryLine_ID
     */
    String COLUMNNAME_M_InventoryLine_ID = "M_InventoryLine_ID";
    /**
     * Column name MovementQty
     */
    String COLUMNNAME_MovementQty = "MovementQty";

    /**
     * Get Date Material Policy. Time used for LIFO and FIFO Material Policy
     */
    Timestamp getDateMaterialPolicy();

    /**
     * Set Date Material Policy. Time used for LIFO and FIFO Material Policy
     */
    void setDateMaterialPolicy(Timestamp DateMaterialPolicy);

    /**
     * Set Auto Generated
     */
    void setIsAutoGenerated(boolean IsAutoGenerated);

    /**
     * Get Auto Generated
     */
    boolean isAutoGenerated();

    /**
     * Get Attribute Set Instance. Product Attribute Set Instance
     */
    int getAttributeSetInstanceId();

    /**
     * Set Attribute Set Instance. Product Attribute Set Instance
     */
    void setAttributeSetInstanceId(int M_AttributeSetInstance_ID);

    /**
     * Get Phys.Inventory Line. Unique line in an Inventory document
     */
    int getInventoryLineId();

    /**
     * Set Phys.Inventory Line. Unique line in an Inventory document
     */
    void setInventoryLineId(int M_InventoryLine_ID);

    I_M_InventoryLine getM_InventoryLine() throws RuntimeException;

    /**
     * Get Movement Quantity. Quantity of a product moved.
     */
    BigDecimal getMovementQty();

    /**
     * Set Movement Quantity. Quantity of a product moved.
     */
    void setMovementQty(BigDecimal MovementQty);

}
