package org.compiere.model;

import java.math.BigDecimal;
import java.sql.Timestamp;
import org.idempiere.common.util.KeyNamePair;

/**
 * Generated Interface for M_InOutLineMA
 *
 * @author iDempiere (generated)
 * @version Release 5.1
 */
public interface I_M_InOutLineMA {

  /** TableName=M_InOutLineMA */
  String Table_Name = "M_InOutLineMA";

  /** AD_Table_ID=762 */
  int Table_ID = 762;

    /** AccessLevel = 1 - Org */
  BigDecimal accessLevel = BigDecimal.valueOf(1);

  /** Load Meta Data */

    /** Column name DateMaterialPolicy */
  String COLUMNNAME_DateMaterialPolicy = "DateMaterialPolicy";
    /** Column name IsAutoGenerated */
  String COLUMNNAME_IsAutoGenerated = "IsAutoGenerated";
  /** Column name M_AttributeSetInstance_ID */
  String COLUMNNAME_M_AttributeSetInstance_ID = "M_AttributeSetInstance_ID";
  /** Column name M_InOutLine_ID */
  String COLUMNNAME_M_InOutLine_ID = "M_InOutLine_ID";
  /** Column name M_InOutLineMA_UU */
  String COLUMNNAME_M_InOutLineMA_UU = "M_InOutLineMA_UU";
  /** Column name MovementQty */
  String COLUMNNAME_MovementQty = "MovementQty";

    /** Get Date Material Policy. Time used for LIFO and FIFO Material Policy */
  Timestamp getDateMaterialPolicy();

  /** Set Date Material Policy. Time used for LIFO and FIFO Material Policy */
  void setDateMaterialPolicy(Timestamp DateMaterialPolicy);

    /** Set Auto Generated */
  void setIsAutoGenerated(boolean IsAutoGenerated);

    /** Set Attribute Set Instance. Product Attribute Set Instance */
  void setM_AttributeSetInstance_ID(int M_AttributeSetInstance_ID);

  /** Get Attribute Set Instance. Product Attribute Set Instance */
  int getMAttributeSetInstance_ID();

    /** Get Shipment/Receipt Line. Line on Shipment or Receipt document */
  int getM_InOutLine_ID();

  /** Set Shipment/Receipt Line. Line on Shipment or Receipt document */
  void setM_InOutLine_ID(int M_InOutLine_ID);

  I_M_InOutLine getM_InOutLine() throws RuntimeException;

    /** Get Movement Quantity. Quantity of a product moved. */
  BigDecimal getMovementQty();

  /** Set Movement Quantity. Quantity of a product moved. */
  void setMovementQty(BigDecimal MovementQty);

}
